FROM golang:1.25-alpine AS builder

WORKDIR /app

ENV CGO_ENABLED=0 GOOS=linux

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -ldflags="-s -w" -o gateway ./...

FROM alpine:3.20

WORKDIR /app

COPY --from=builder /app/gateway ./gateway

ENV PORT=3000
EXPOSE 3000

CMD ["./gateway"]
